version: '3.8'

services:
  mysql1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db1
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
    ports:
      - "3306:3306"
    volumes:
      - ./mysql1_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=ROW
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user1", "-ppass1"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql2:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db2
      MYSQL_USER: user2
      MYSQL_PASSWORD: pass2
    ports:
      - "3307:3306"
    volumes:
      - ./mysql2_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=ROW
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user2", "-ppass2"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql3:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db3
      MYSQL_USER: user3
      MYSQL_PASSWORD: pass3
    ports:
      - "3308:3306"
    volumes:
      - ./mysql3_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
    command: --server-id=3 --log-bin=mysql-bin --binlog-format=ROW
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user3", "-ppass3"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql4:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db4
      MYSQL_USER: user4
      MYSQL_PASSWORD: pass4
    ports:
      - "3309:3306"
    volumes:
      - ./mysql4_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
    command: --server-id=4 --log-bin=mysql-bin --binlog-format=ROW
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user4", "-ppass4"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql5:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db5
      MYSQL_USER: user5
      MYSQL_PASSWORD: pass5
    ports:
      - "3310:3306"
    volumes:
      - ./mysql5_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
    command: --server-id=5 --log-bin=mysql-bin --binlog-format=ROW
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user5", "-ppass5"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql6:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db6
      MYSQL_USER: user6
      MYSQL_PASSWORD: pass6
    ports:
      - "3311:3306"
    volumes:
      - ./mysql6_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
    command: --server-id=6 --log-bin=mysql-bin --binlog-format=ROW
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user6", "-ppass6"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql7:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db7
      MYSQL_USER: user7
      MYSQL_PASSWORD: pass7
    ports:
      - "3312:3306"
    volumes:
      - ./mysql7_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
    command: --server-id=7 --log-bin=mysql-bin --binlog-format=ROW
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user7", "-ppass7"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql8:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db8
      MYSQL_USER: user8
      MYSQL_PASSWORD: pass8
    ports:
      - "3313:3306"
    volumes:
      - ./mysql8_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/mysql/my.cnf
    command: --server-id=8 --log-bin=mysql-bin --binlog-format=ROW
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user8", "-ppass8"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  debezium:
    image: debezium/connect:${DEBEZIUM_VERSION}
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql1_data:
  mysql2_data:
  mysql3_data:
  mysql4_data:
  mysql5_data:
  mysql6_data:
  mysql7_data:
  mysql8_data: